### ISSUE TITLE
Kindly consider migrating this work to ROS2-Humble or Foxy versions

### ISSUE THREAD

**Issue by a2a4** [boschresearch/mrp_bench#3]
Colcon build command fails because there were lot of changes from the time this code was built and the updated ros2 galactic , which is currently distributed for core ros repositories! This is causing a problem while executing "colcon build". I opened anothe parallel issue about the same. Please help me if I'm wrong. Thanks.

**Comment by palmieri** [comment]
This issue won't be solved at the moment. Closing it.
